swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
basePath: /SERVICE_NAME

paths:
  /apiEndpoint:
    post:
      tags:
      - Route
      summary: "Sample Route"
      description: "Sample Route"
      operationId: sampleController

      consumes:
      - "application/json"
      produces:
      - "application/json"

      parameters:
      - in: 'header'
        name: 'Authorization'
        type: 'string'
        required: true
        description: 'auth_key'
      - in: "body"
        name: "body"
        description: "id"
        required: true
        schema:
          $ref: "#/definitions/sampleData"     
        
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      x-swagger-router-controller: "sampleController"
      
definitions:
  sampleData:
    type: "object" 
    properties:  
      name:
        type: string
      age:
        type: integer
      address:
         type: string

  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      data:
        type: object
    example:
      code: 0
      data: { 'response': 'api_response_data' }

  ErrorResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
